package service

// Code generated by protoc-gen-parse. DO NOT EDIT.
import (
	"luyaops/fw/common/etcd"
	"luyaops/fw/common/register"
)

var apiJson = "[{\"Package\":\"say\",\"Service\":\"Say\",\"Method\":{\"name\":\"Echo\",\"input_type\":\"say.HelloRequest\",\"output_type\":\"say.EchoResponse\",\"options\":{}},\"Pattern\":{\"Verb\":\"GET\",\"Path\":\"/v1/say/echo\",\"Body\":\"\"},\"Options\":{}},{\"Package\":\"say\",\"Service\":\"Say\",\"Method\":{\"name\":\"Hello\",\"input_type\":\"say.HelloRequest\",\"output_type\":\"say.EchoResponse\",\"options\":{}},\"Pattern\":{\"Verb\":\"POST\",\"Path\":\"/v1/say/hello\",\"Body\":\"*\"},\"Options\":{}}]"
var store = etcd.NewStore("localhost:2379")
var server = "say"

func init() {
	register.Register(store, server, apiJson)
}
